name: CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-2019

    steps:

      - run: msbuild.exe /?
        shell: pwsh
      - run: Get-VisualStudioComponents
        shell: pwsh
       
