name: CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-2019

    steps:
      - run: $PSScriptRoot\VisualStudioHelpers.ps1
        shell: pwsh
      - run: Get-VisualStudioProduct
        shell: pwsh
      - run: Get-VisualStudioComponents
        shell: pwsh
       
